// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StackOverflowApi.Models;

namespace StackOverflowApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StackOverFlow.Models.AnswersPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AnswerContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfPost")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("QuestionPostId")
                        .HasColumnType("integer");

                    b.Property<int>("UpDownVoteAnswer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionPostId");

                    b.ToTable("AnswersPost");
                });

            modelBuilder.Entity("StackOverflowApi.Models.QuestionPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfPost")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfViews")
                        .HasColumnType("integer");

                    b.Property<int>("UpDownVoteQuestion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuestionPosts");
                });

            modelBuilder.Entity("StackOverFlow.Models.AnswersPost", b =>
                {
                    b.HasOne("StackOverflowApi.Models.QuestionPost", "QuestionPost")
                        .WithMany("AnswersPosts")
                        .HasForeignKey("QuestionPostId");
                });
#pragma warning restore 612, 618
        }
    }
}
